name: $(Major).$(Minor).$(Patch)

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/Callisto.HealthCheck/Callisto.HealthCheck.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/Callisto.HealthCheck/Callisto.HealthCheck.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PackageVersion'

- task: DotNetCoreCLI@2
  displayName: 'Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '639b609b-649b-4066-910d-c026c8cb1bbc'